pulseaudio control

diff --git a/bin/mvolume b/bin/mvolume
--- a/bin/mvolume
+++ b/bin/mvolume
@@ -22,36 +22,41 @@ command_exists() {
 }
 
 # pulseaudio?
-# http://ubuntuforums.org/showpost.php?p=10232181&postcount=9
-if command_exists pacmd ; then
-  if ! command_exists awk ; then
-    echo "awk is required." && exit 1
-  fi
+# see also: http://ubuntuforums.org/showpost.php?p=10232181&postcount=9
+if command_exists pactl ; then
   case $1 in
-    # Note: 655 is about 1% of 65536
-    +|raise) opt='$1~/set-sink-volume/{system ("pacmd "$1" "$2" "$3+655)}' ;;
-    -|lower) opt='$1~/set-sink-volume/{system ("pacmd "$1" "$2" "$3-655)}' ;;
-    /|mute)  opt='$1~/set-sink-mute/{system ("pacmd "$1" "$2" "($3=="yes"?"no":"yes"))}' ;;
+
+    # pulseaudio 8.0 (Ubuntu 16.04)
+    +|raise) pactl set-sink-volume @DEFAULT_SINK@ +1% ;;
+    -|lower) pactl set-sink-volume @DEFAULT_SINK@ -1% ;;
+    /|mute)  pactl set-sink-mute   @DEFAULT_SINK@ toggle ;;
+
+    # pulseaudio 4.0 (Ubuntu 14.04)
+    # +|raise) pactl set-sink-volume @DEFAULT_SINK@ -- +1% ;;
+    # -|lower) pactl set-sink-volume @DEFAULT_SINK@ -- -1% ;;
+    # /|mute)  pactl set-sink-mute   @DEFAULT_SINK@ toggle ;;
+
+    # pulseaudio 1.1 (Ubuntu 12.04)
+    # +|raise) pactl set-sink-volume @DEFAULT_SINK@ -- +1% ;;
+    # -|lower) pactl set-sink-volume @DEFAULT_SINK@ -- -1% ;;
+    # /|mute)
+    #   toggle=`pacmd dump | awk '$1~/set-sink-mute/{ print ($3 == "no") }'`
+    #   pactl set-sink-mute @DEFAULT_SINK@ $toggle ;;
+
     *) show_usage ;;
   esac
-  cmd="pacmd dump|awk '$opt'"
-  # Note, Ubuntu 12.04 required that:
-  # cmd="pacmd dump|awk --non-decimal-data '$opt'"
 
 # alsa mixer?
 elif command_exists amixer ; then
   case $1 in
-    +|raise) cmd="amixer -q sset Master 1%+"    ;;
-    -|lower) cmd="amixer -q sset Master 1%-"    ;;
-    /|mute)  cmd="amixer -q sset Master toggle" ;;
+    +|raise) amixer -q sset Master 1%+ ;;
+    -|lower) amixer -q sset Master 1%- ;;
+    /|mute)  amixer -q sset Master toggle ;;
     *) show_usage ;;
   esac
 
 # no sound controller available
 else
-  echo "could not find pulseaudio 'pacmd' nor alsa 'amixer'." && exit 1
+  echo "could not find pulseaudio 'pactl' nor alsa 'amixer'." && exit 1
 fi
-
-echo $cmd
-eval $cmd > /dev/null
 
